# Generated by Django 5.0.6 on 2024-06-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_basketitems_basket_oject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitems',
            old_name='basket_oject',
            new_name='basket_object',
        ),
    ]
